//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class GameSettings
{
	public float SecondsToSolve = 300;
	public int NumStrikesToLose = 5;
	public int Difficulty = 3;
}

